### ISSUE TITLE
Only works in Anaconda Prompt on Windows

### ISSUE THREAD

**Issue by robintw** [conda-forge/sixs-feedstock#1]
I've tested this on two Windows machines, and on both this only works properly from within the _Anaconda Prompt_ as opposed to the normal command prompt. When running from the normal Windows command prompt I get errors about various DLLs missing:
- `libwinpthread-1.dll`
- `libgcc_s_seh-1.dll`
- `libquadmath-0.dll`
- `libgfortran-3.dll`

If those are added manually to the same folder that `sixs.exe` is located in, then it works fine.

I've done some investigation into this, compared the environment variables between the prompts and found that the Anaconda Prompt adds `C:\Anaconda3\Library\mingw-w64\bin` to the `PATH` variable. Interestingly, looking at `activate.bat` it seems that these come from running `conda ..activate cmd.exe root` - which is a command I'd never come across before!

When installing Anaconda I definitely ticked the box that added the relevant locations to the `PATH` variable, but of course the `mingw-w64` path didn't exist then as I hadn't installed that package.

Is there any way around this? Can I somehow set my recipe to make sure the DLLs from mingw are copied to the right locations (eg. `Anaconda3/Library/bin`, which would already be in the `PATH`)?

Cc to @danclewley for previous experience of sixs on Windows, and @ocefpaf for conda expertise.

**Comment by ocefpaf** [comment]
> Cc to @danclewley for previous experience of sixs on Windows, and @ocefpaf for conda expertise.

@robintw that is the expected behavior with `conda`. I don't think `Anaconda3/Library/bin` is available in the "normal" command prompt unless you told anaconda to add it to the path, and many users don't do that to avoid conflicts.

My recommendation is to always open the "anaconda prompt" and also to work with envs to ensure the right env vars are activated in a safe way.

**Comment by danclewley** [comment]
Was just writing this when @ocefpaf replied:

It works on a normal prompt if you install to a new environment and then activate this.

From some of the issues I've seen on https://github.com/conda-forge/gdal-feedstock I was under the impression the recommended practice was always to install to a new environment with forcing the activate script to be run as one of the reasons for this.

**Comment by ocefpaf** [comment]
> From some of the issues I've seen on https://github.com/conda-forge/gdal-feedstock I was under the impression the recommended practice was always to install to a new environment with forcing the activate script to be run as one of the reasons for this.

Yes. That is the best practice.

**Comment by danclewley** [comment]
> Yes. That is the best practice.

In this case @robintw, do you want to close this issue and make sure the Py6S install instructions recommend installing in a new environment.

**Comment by robintw** [comment]
Yup, sounds sensible.

Thanks both of you.
