### ISSUE TITLE
Windows builds failing with CMake error

### ISSUE THREAD

**Issue by robintw** [conda-forge/sixs-feedstock#12]
The Windows builds are currently failing. This seems to be since the introduction of new GCC (and other compiler?) versions by conda-forge a while ago (this affected #9 too, which was automatically opened at the time - and the problem was never solved).

The error seems to be a CMake error about not being able to build with MSYS Makefiles because the right stuff isn't installed. This could be as simple as needing to add an extra dependency, but I don't know what needs adding.

```
(%BUILD_PREFIX%) %SRC_DIR%>cmake -G "MSYS Makefiles" -D CMAKE_INSTALL_PREFIX=%PREFIX%\Library %SRC_DIR% 
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program. 
-- Configuring incomplete, errors occurred!
```

**Comment by robintw** [comment]
@ocefpaf Thanks for your help merging the other PR. I've added this issue now. I'm afraid you're pretty-much my only contact within the conda-forge organisation (hence why I keep pestering you - sorry!), so if you know anyone else who might be able to help with these CMake errors then it'd be great if you could bring this issue to their attention. Thanks!

**Comment by ocefpaf** [comment]
Pinging @isuruf here but he is quite busy and I don't like to divert him (too much) from his studies ;-p

**Comment by isuruf** [comment]
You probably need to add `posix` dependency to your `build` requirements. (This was there implicitly a while ago in Azure images and we sanitized the Azure images)

**Comment by robintw** [comment]
Thanks so much @isuruf - that has solved it immediately :)
