### ISSUE TITLE
Regression with latest version - Segmentation fault on Linux in some configurations

### ISSUE THREAD

**Issue by robintw** [conda-forge/sixs-feedstock#5]
**Summary:** There has been a regression in the latest version of the sixs conda package, which means that the code will sometimes crash with a segmentation fault. This is not due to changes in the 6S code itself (there have been no changes), but in the changes in the conda package which occurred late last year.

**Details:**
Installing the latest version of the `sixs` package from conda-forge, and then running one of the 6S provided example files (`Example_In_3.txt` - available at http://rtwilson.com/downloads/Example_In_3.txt for convenience) leads to a segmentation fault. For example:

```
robintw@linux:~$ conda create -n test-sixs -c conda-forge sixs
--snip--
The following NEW packages will be INSTALLED:

    libgcc-ng:      7.3.0-hdf63c60_0  conda-forge
    libgfortran-ng: 7.2.0-hdf63c60_3  conda-forge
    libstdcxx-ng:   7.3.0-hdf63c60_0  conda-forge
    sixs:           1.1-h1c2f66e_1001 conda-forge
--snip--
robintw@linux:~$ conda activate test-sixs
(test-sixs) robintw@linux:~$ sixs < Example_In_3.txt 
Segmentation fault
```

This is automatically installing the latest version, with build number 1001. If I manually install the previous version, with build number 1, then it works fine:

```
(test-sixs) robintw@linux:~$ conda install -c conda-forge sixs=1.1=h26a2512_1
--snip--
## Package Plan ##

  environment location: /home/robintw/anaconda3/envs/test-sixs

  added / updated specs: 
    - sixs==1.1=h26a2512_1


The following NEW packages will be INSTALLED:

    libgfortran: 3.0.0-1           conda-forge

The following packages will be DOWNGRADED:

    sixs:        1.1-h1c2f66e_1001 conda-forge --> 1.1-h26a2512_1 conda-forge
--snip--
(test-sixs) robintw@linux:~$ sixs < Example_In_3.txt 
******************************* 6SV version 1.1 *******************************
*                                                                             *
*                       geometrical conditions identity                       *
*                       -------------------------------                       *
*                       t.m.     observation                                  *
*                month:  5 day :   9 universal time: 11.22 (hh.dd)            *
*               latitude:   40.00 deg        longitude:   30.00 deg           *
*   solar zenith angle:   28.09 deg  solar azimuthal angle:      222.02 deg   *
*   view zenith angle:     0.00 deg  view azimuthal angle:         0.00 deg   *
--snip-- (there is a lot more output after this, but no segfault)
```

The change to build number 1001 seemed to occur in the merging of PR #4, which apparently upgraded GCC and OpenBLAS. I'm pinging @danclewley and @mariusvniekerk as they commented on and merged the PR.

Interestingly, the latest version works fine with some of the example input files provided with 6S - including `Example_Input_1.txt` which is used as part of the tests of the package. `Example_Input_3.txt` uses some more complex functionality of the package, and it seems to be this part that is failing in the latest packaged version.

I've had a very brief play with `gdb`, but the conda compiled version of 6S doesn't have debug symbols in it, so there's a limit to what I can do. I've compiled 6S on my machine many times, and I've never had segmentation faults - so I assume it is something in the configuration of the conda build process for this package, but I don't really understand it.

I'm not really sure where to go next, but a few thoughts:

1. Is it possible to rollback to build 1, so that there is a working version for people to install from conda while we try and fix this?
2. I think we should add a test using `Example_In_3.txt` to try and catch these sort of bugs in future - this would also help the CI tell us when we've fixed this.
3. Is there any way to replicate the exact conda build environment on a local machine (or cloud machine, or docker container, or whatever) to try and debug what is going on here? I can't promise I'll be much help, as I'm not hugely experienced with Fortran compilation issues, but I can try and help.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/robintw/anaconda3/envs/test-sixs:
#
# Name                    Version                   Build  Channel
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
sixs                      1.1                  h26a2512_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test-sixs
    active env location : /home/robintw/anaconda3/envs/test-sixs
            shell level : 1
       user config file : /home/robintw/.condarc
 populated config files : 
          conda version : 4.5.5
    conda-build version : not installed
         python version : 3.6.0.final.0
       base environment : /home/robintw/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/robintw/anaconda3/pkgs
                          /home/robintw/.conda/pkgs
       envs directories : /home/robintw/anaconda3/envs
                          /home/robintw/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.19.1 CPython/3.6.0 Linux/3.13.0-36-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by robintw** [comment]
Is there anyone else who can assist with this (eg. with rolling back to the previous version for the moment): @conda-forge-admin @ocefpaf

**Comment by ocefpaf** [comment]
Let me try to implement that example as a test in the feedstock build. Hold on...

---
Edit: we cannot roll back b/c any new version would use the same new compilers. We can remove that version with the new compilers but then this package would be incompatible with conda-forge current packages.

**Comment by ocefpaf** [comment]
I remove the broken Linux package. Based on #6 I believe that OS X is fine, not 100% sure about Windows yet. Can you check if I got it right?

https://anaconda.org/conda-forge/sixs/files?channel=gcc7&version=1.1

**Comment by robintw** [comment]
I'm slightly confused - was that link showing packages that should be removed, or should be kept? Both the packages listed at https://anaconda.org/conda-forge/sixs/files?channel=gcc7&version=1.1 seem to be build 1001, and I think that was the one that needed removing, going back to build 1.

**Comment by ocefpaf** [comment]
> I'm slightly confused - was that link showing packages that should be removed, or should be kept? Both the packages listed at [anaconda.org/conda-forge/sixs/files?channel=gcc7&version=1.1](https://anaconda.org/conda-forge/sixs/files?channel=gcc7&version=1.1) seem to be build 1001, and I think that was the one that needed removing, going back to build 1.

That one is marked as `broken`, so the previous build will be preferred.

**Comment by robintw** [comment]
Ah, I hadn't seen the little 'broken' tag. That sounds good. I'll double-check Windows myself and get back to you as to whether that needs to be tagged as broken or not.
